export const FRACTAL_LEVELS_MAP: {[key: number]: string} = {
  1: 'Volcanic',
  2: 'Uncategorized',
  3: 'Snowblind',
  4: 'Urban Battleground',
  5: 'Swampland',
  6: 'Cliffside',
  7: 'Aquatic Ruins',
  8: 'Underground Facility',
  9: 'Molten Furnace',
  10: 'Molten Boss',
  11: 'Deepstone',
  12: 'Siren\'s Reef',
  13: 'Chaos',
  14: 'Aetherblade',
  15: 'Thaumanova Reactor',
  16: 'Twilight Oasis',
  17: 'Molten Furnace',
  18: 'Captain Mai Trin Boss',
  19: 'Volcanic',
  20: 'Solid Ocean',
  21: 'Cliffside',
  22: 'Nightmare',
  23: 'Shattered Observatory',
  24: 'Sunqua Peak',
  25: 'Silent Surf',
  26: 'Aquatic Ruins',
  27: 'Snowblind',
  28: 'Volcanic',
  29: 'Underground Facility',
  30: 'Chaos',
  31: 'Urban Battleground',
  32: 'Swampland',
  33: 'Deepstone',
  34: 'Thaumanova Reactor',
  35: 'Solid Ocean',
  36: 'Uncategorized',
  37: 'Siren\'s Reef',
  38: 'Chaos',
  39: 'Molten Furnace',
  40: 'Molten Boss',
  41: 'Twilight Oasis',
  42: 'Captain Mai Trin Boss',
  43: 'Thaumanova Reactor',
  44: 'Solid Ocean',
  45: 'Aetherblade',
  46: 'Cliffside',
  47: 'Nightmare',
  48: 'Shattered Observatory',
  49: 'Sunqua Peak',
  50: 'Silent Surf',
  51: 'Snowblind',
  52: 'Volcanic',
  53: 'Underground Facility',
  54: 'Siren\'s Reef',
  55: 'Thaumanova Reactor',
  56: 'Swampland',
  57: 'Urban Battleground',
  58: 'Molten Furnace',
  59: 'Twilight Oasis',
  60: 'Solid Ocean',
  61: 'Aquatic Ruins',
  62: 'Uncategorized',
  63: 'Chaos',
  64: 'Thaumanova Reactor',
  65: 'Aetherblade',
  66: 'Urban Battleground',
  67: 'Deepstone',
  68: 'Cliffside',
  69: 'Molten Boss',
  70: 'Aetherblade Boss',
  71: 'Captain Mai Trin Boss',
  72: 'Nightmare',
  73: 'Shattered Observatory',
  74: 'Sunqua Peak',
  75: 'Silent Surf',
  76: 'Aquatic Ruins',
  77: 'Swampland',
  78: 'Siren\'s Reef',
  79: 'Uncategorized',
  80: 'Solid Ocean',
  81: 'Underground Facility',
  82: 'Thaumanova Reactor',
  83: 'Molten Furnace',
  84: 'Deepstone',
  85: 'Urban Battleground',
  86: 'Snowblind',
  87: 'Twilight Oasis',
  88: 'Chaos',
  89: 'Swampland',
  90: 'Molten Boss',
  91: 'Uncategorized',
  92: 'Volcanic',
  93: 'Snowblind',
  94: 'Cliffside',
  95: 'Captain Mai Trin Boss',
  96: 'Aetherblade',
  97: 'Nightmare',
  98: 'Shattered Observatory',
  99: 'Sunqua Peak',
  100: 'Silent Surf',
};
